name: Prod in Flight

on:
  push:
    branches: [ master ]

jobs:
  test:

    name: Build and Run Mix Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies for build
      run: sudo apt-get install -y libncurses-dev libtinfo5
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.0' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      working-directory: .
      run: mix deps.get
    - name: Generate Mock Certs
      working-directory: .
      run: mix sparrow.certs.dev
    - name: Run tests
      env:
        MIX_ENV: test
      working-directory: .
      run: mix test
